name: 'github-contentful-readme'
description: 'Update your profile readme from the Contentful headless CMS'
inputs:
  contentfulAccessToken:
    description: 'Contentful content access token'
    required: true
    default: ''
  contentfulSpaceId:
    description: 'Contentful space ID (not the name)'
    required: true
    default: ''
  headerKey:
    description: 'The name of the Key-Value pair in Contentful with the header text'
    required: true
    default: ''
  subheaderKey:
    description: 'The name of the Key-Value pair in Contentful with the subheader text'
    required: false
    default: ''
  footerKey:
    description: 'The name of the Key-Value pair in Contentful with the footer text'
    required: false
    default: ''
  path:
    description: 'Path of your README.md file.'
    required: false
    default: 'README.md'
  ref:
    description: 'Override the default branch/tag ref.'
    required: false
    default: 'master'
  imageSize:
    description: 'Length (in pixels) of each side of the square image.'
    required: false
    default: '200'
  excludeActivity:
    description: "Types of event to exclude from the recent activity table. Read more on this repository's README.md."
    required: false
    default: '[]'
  excludeRepo:
    description: "Repositories to exclude from the recent activity table. Read more on this repository's README.md."
    required: false
    default: '[]'

branding:
  icon: activity
  color: green

runs:
  using: 'node12'
  main: 'dist/index.js'